#!/bin/bash

asciinema rec /home/$USER/$1.cast

echo -e "Enter 1 to Create an SVG\nEnter 2 to create a GIF"

valid_option=false

# Not Working Needs Modification
# CURRENT_TERMINAL_WIDTH=$(tput cols)
#CURRENT_TERMINAL_HEIGHT=$(tput lines)

while [ "$valid_option" = false ]; do
  echo "What to do with the recording: "
  read option

  case "$option" in
    "1")
    echo "Converting your recording to SVG..."
    svg-term --in /home/$USER/$1.cast --out /home/$USER/$1.svg --window --width 120 --height 20 --no-optimize
    mv /home/$USER/$1.svg /home/$USER/Pictures/terminal_SVG
    valid_option=true
      ;;
    "2")
      echo "Converting your recording to GIF..."
      echo -e "Do you want to apply any other theme? Press y/Y for a new theme. Else press anything..."
      read themevar
      if [ "$themevar" = "y" ] || [ "$themevar" = "Y" ]; then
	  echo -e "Available themes are\n1. ASCIINEMA\n2. Dracula\n3. Monokai\n4. Solarized Dark\n5. Solarized Light."
	  Voption=false

          while [ "$Voption" = false ]; do
                echo "Enter an option:"
                read themenum

		  case "$themenum" in
		    "1")
		      agg --theme asciinema /home/$USER/$1.cast /home/$USER/$1.gif
		      Voption=true
		      ;;
		    "2")
		      agg --theme dracula /home/$USER/$1.cast /home/$USER/$1.gif
		      Voption=true
		      ;;
	            "3")
		      agg --theme monokai /home/$USER/$1.cast /home/$USER/$1.gif
		      Voption=true
		      ;;
		    "4")
		      agg --theme solarized-dark /home/$USER/$1.cast /home/$USER/$1.gif
		      Voption=true
		      ;;
		    "5")
		      agg --theme solarized-light /home/$USER/$1.cast /home/$USER/$1.gif
		      Voption=true
		      ;;
		    *)
		      echo "Invalid option. Please try again."
		      ;;
		  esac
		done

      else
	  echo "Proceding with Default theme.."
	  agg /home/$USER/$1.cast /home/$USER/$1.gif
      fi

      mv /home/$USER/$1.gif /home/$USER/Pictures/terminal_SVG
      valid_option=true
      ;;
    *)
      echo "Invalid option. Please try again."
      ;;
  esac
done
rm /home/$USER/$1.cast
