#!/bin/bash
echo "Help"
echo "===="


echo "This program is used to create an SVG/GIF for the terminal recording, based on the current terminal width and height."

echo "To create a recording, run : recordterm <filename>"
echo
echo "Now, you may do whatever you want to record on the terminal. Once finished, press CTRL + D to stop recording. It will create an SVG/GIF of the file (as per the onscreen choice) and move it to a common place, in /home/$USER/Pictures/terminal_SVG folder."

echo  "It will also remove your .cast files, that was created as part of the underlying `asciinema` recording."
echo
echo -e "Use 'editshow' to edit the captions. This opens the file in nano editor\nUse 'recordterm <filename>' to create an svg\nUse 'showing' to print the caption during any recording session."
